---
name: cantor
version: 17.08.1
summary: KDE Frontend to Mathematical Software
description: Cantor is a front-end to powerful mathematics and statistics packages.
    Cantor integrates them into the KDE Platform and provides a nice, worksheet-based,
    graphical user interface. It supports environments for KAlgebra, Lua, Maxima,
    R, Sage, Octave, Python, Scilab, and Qalculate!
confinement: strict
grade: stable
apps:
    cantor:
        command: kf5-launch cantor
        plugs:
        - kde-frameworks-5-plug
        - home
        - x11
        - opengl
        - network
        - network-bind
        - unity7
        - pulseaudio
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.cantor
        bus: session
plugs:
    kde-frameworks-5-plug:
        content: kde-frameworks-5-all
        interface: content
        default-provider: kde-frameworks-5
        target: kf5
parts:
    cantor:
        after:
        - kde-frameworks-5-dev
        - kde-frameworks-5-env
        plugin: cmake
        build-packages:
        - julia
        - kdoctools-dev
        - libanalitza-dev
        - libglib2.0-dev
        - libkf5kdelibs4support-dev
        - liblapack3
        - libluajit-5.1-dev
        - libqalculate-dev
        - libspectre-dev
        - pkg-config
        - python-dev
        - python3-dev
        - r-base-core
        - libpulse0
        source: https://download.kde.org/stable/applications/17.08.1/src/cantor-17.08.1.tar.xz
        configflags:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
